# Generated by Django 4.0.8 on 2023-01-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
