# Generated by Django 3.2.14 on 2023-01-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_server_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.BigIntegerField(default=0)),
                ('last_date', models.DateField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='max_traffic',
            field=models.BigIntegerField(default=26214400),
        ),
        migrations.AddField(
            model_name='user',
            name='used_traffic',
            field=models.BigIntegerField(default=0),
        ),
    ]
