# Generated by Django 3.2.14 on 2023-02-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_daycount_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='server',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
