# Generated by Django 3.2.14 on 2023-02-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230212_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='max_traffic',
            field=models.BigIntegerField(default=200000000000),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_traffic',
            field=models.BigIntegerField(default=25000000000),
        ),
    ]
