# Generated by Django 3.2.14 on 2023-02-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='historical_traffic',
            field=models.BigIntegerField(default=0),
        ),
    ]
