# Generated by Django 3.2.14 on 2023-03-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_domain_historical_traffic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='is_full',
        ),
    ]
