# Generated by Django 3.2.14 on 2023-03-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_telegramblacklist_telegrammessagetrottle_telegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramblacklist',
            name='username',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
