# Generated by Django 3.2.14 on 2023-03-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_telegramadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramadmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
