# Generated by Django 3.2.14 on 2023-03-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_telegramadmin_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permamant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='expire_at',
            field=models.BigIntegerField(null=True),
        ),
    ]
