# Generated by Django 3.2.14 on 2023-03-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20230312_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='permamant',
            new_name='permanant',
        ),
    ]
