# Generated by Django 3.2.14 on 2023-03-20 17:34

import backend.customs.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_trafficusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficusage',
            name='timestamp',
            field=models.BigIntegerField(default=backend.customs.generators.current_int_timestamp),
        ),
    ]
