# Generated by Django 3.2.14 on 2023-04-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20230401_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramadmin',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
