# Generated by Django 3.2.14 on 2023-05-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20230505_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminbill',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='adminbill',
            name='multipler',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='adminbill',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
