# Generated by Django 3.2.14 on 2023-06-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_alter_noderate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noderate',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_rates', to='user.node'),
        ),
    ]
