# Generated by Django 3.2.14 on 2023-08-14 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_alter_absencestatus_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='arvanaccount',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='arvan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='user.arvanaccount'),
        ),
        migrations.AddField(
            model_name='domain',
            name='arvan_used_traffic',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='rank',
            field=models.IntegerField(default=10),
        ),
    ]
