# Generated by Django 3.2.14 on 2023-09-01 14:06

import backend.customs.generators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_auto_20230814_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField()),
                ('change', models.BigIntegerField()),
                ('timestamp', models.IntegerField(default=backend.customs.generators.current_int_timestamp)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to='user.telegramadmin')),
            ],
        ),
    ]
