# Generated by Django 3.2.14 on 2023-01-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230119_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_traffic',
            field=models.BigIntegerField(default=26843545600),
        ),
    ]
