# Generated by Django 3.2.14 on 2023-01-20 19:46

import backend.customs.generators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230120_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='client',
        ),
        migrations.AlterField(
            model_name='user',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.server'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=backend.customs.generators.generate_uuid, max_length=50),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
