# Generated by Django 3.2.14 on 2023-01-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230120_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
