# Generated by Django 3.2.14 on 2023-02-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20230212_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='live_users',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='max_users',
        ),
        migrations.AddField(
            model_name='domain',
            name='max_traffic',
            field=models.BigIntegerField(default=214748364800),
        ),
        migrations.AddField(
            model_name='domain',
            name='reserved_traffic',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='used_traffic',
            field=models.BigIntegerField(default=0),
        ),
    ]
