# Generated by Django 3.2.14 on 2023-02-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20230220_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expire_at',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
