# Generated by Django 3.2.14 on 2023-03-20 17:00

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_rename_permamant_user_permanant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.BigIntegerField(default=0)),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='user.user')),
            ],
        ),
    ]
