# Generated by Django 3.2.14 on 2023-04-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_trafficusage_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramadmin',
            name='created_vol',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramadmin',
            name='main_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.telegramadmin'),
        ),
        migrations.CreateModel(
            name='AdminBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_vol', models.BigIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='user.telegramadmin')),
            ],
        ),
    ]
