# Generated by Django 3.2.14 on 2023-04-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_telegramadmin_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramadmin',
            name='created_vol',
        ),
    ]
