# Generated by Django 3.2.14 on 2023-05-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20230411_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='private_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
