# Generated by Django 3.2.14 on 2023-05-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_systembalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systembalance',
            name='balance',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
    ]
