# Generated by Django 3.2.14 on 2023-05-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_telegramadmin_untrusted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramadmin',
            name='untrusted',
            field=models.BooleanField(default=True),
        ),
    ]
