# Generated by Django 3.2.14 on 2023-05-22 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_alter_telegramadmin_untrusted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbanLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('password', models.TextField(null=True)),
                ('abanlink', models.TextField(null=True)),
                ('access_token', models.TextField(null=True)),
                ('api_key', models.TextField(null=True)),
                ('balance', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArvanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('api_key', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('state', models.IntegerField(choices=[(0, 'created'), (1, 'waiting'), (2, 'success'), (3, 'done'), (4, 'timed_out'), (5, 'failed')], default=1)),
                ('token', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='user.telegramadmin')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='arvan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node', to='user.arvanaccount'),
        ),
    ]
