# Generated by Django 3.2.14 on 2023-06-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20230522_0745'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telegramuser',
            unique_together={('user', 'telegram_id')},
        ),
    ]
