# Generated by Django 3.2.14 on 2023-06-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_remove_telegramuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 'good'), (0, 'bad')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='user.node')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='user.telegramadmin')),
            ],
        ),
    ]
