# Generated by Django 3.2.14 on 2023-06-11 10:57

import backend.customs.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_noderate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noderate',
            name='created_at',
        ),
        migrations.AddField(
            model_name='noderate',
            name='timestamp',
            field=models.BigIntegerField(default=backend.customs.generators.current_int_timestamp),
        ),
    ]
