# Generated by Django 3.2.14 on 2023-07-01 12:18

import backend.customs.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_absencestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencestatus',
            name='time',
            field=models.BigIntegerField(default=backend.customs.generators.current_int_minute, unique=True),
        ),
    ]
